### ISSUE TITLE
Stopped working with Gnome 3.30

### ISSUE THREAD

**Issue by MateuszKubuszok** [N-Yuki/gnome-shell-extension-workspace-isolated-dash#17] opened 2018-09-18 14:02 UTC
Same issue as with other extensions (e.g. https://github.com/timbertson/gnome-shell-scroll-workspaces/issues/31, https://github.com/franglais125/no-title-bar/issues/93)

Instead of `global.screen` there are `global.workspace_manager` and `global.display` now. In my case it not only breaks isolation but also application searching, so it is noticeable even when I don't use the expension's functionality.

**Comment by adaschma** [comment] 2018-09-20 08:27
Fixed in pull request #18.

**Comment by N-Yuki** [comment] 2018-09-20 08:50
Thanks for the fix.

**Closed as completed by N-Yuki** 2018-09-20 08:50 UTC

**Comment by N-Yuki** [comment] 2018-09-20 09:03
Uploaded new version https://extensions.gnome.org/review/8426 (pending review)
And added new release v15. I've marked it as pre-release until review is completed on the Gnome Extensions site.

**Comment by skewty** [comment] 2018-10-20 19:47
It's been a month..  Has something happened that prevented acceptance during review?  Is there anything we can do to help get this through any faster?

**Comment by N-Yuki** [comment] 2018-10-20 22:33
It was accepted a month ago. I had forgotten to change the status here, but extensions.gnome.org has the latest version now

**Comment by skewty** [comment] 2018-10-21 00:23
Mine wouldn't load and the version compatibility didn't show 3.30.

I cloned, built and installed master and it worked right away though.

I tried just today.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by N-Yuki** [comment] 2018-10-21 00:45
That's odd. It shows up with the latest version for me on the website.
Well, as long as it's working for you now.

**Comment by MuratUrsavas** [comment] 2018-10-22 06:25
For me it's the same problem. The website shows 3.26 as the latest supported version. I've removed and reinstalled but the problem is still there. It doesn't load the extension, which is one of my favorite.

**Comment by MuratUrsavas** [comment] 2018-10-22 06:30
> For me it's the same problem. The website shows 3.26 as the latest supported version. I've removed and reinstalled but the problem is still there. It doesn't load the extension, which is one of my favorite.

Sorry. I guess I've been misguided to here. It's meant for "No Title Bar" extension.
