### ISSUE TITLE
Extension doesn't do anything (gnome 3.14)

### ISSUE THREAD

**Issue by hauberg** [N-Yuki/gnome-shell-extension-workspace-isolated-dash#1] opened 2014-11-30 08:20 UTC
This extension seems to perfectly solve my last issue with gnome-shell, so I would really like to get it running. However, installing it on Fedora 21 (gnome 3.14) doesn't seem to affect the shell in any way. Does it work with 3.14?

Thanks!

**Comment by N-Yuki** [comment] 2014-12-01 22:48
Hi hauberg,

Thanks for reporting this! And sorry about the late response. I had been a little occupied for a few days.

I haven't tested it properly on 3.14, but I had assumed it would be fine, considering the changes made since 3.12.
There are some minor compatibility changes between 3.14.1 and 3.14.2, but could you check which maintenance release (3.14.x) you are running?
I will try test this properly on a system with 3.14 as soon as possible.

Before that, could you check if LookingGlass (press `alt+r`, enter `lg`, then click on the extensions tab) reports any errors on this extension?

Also, do you know how to download/install from GitHub? If so, I could write a debug/testing version of this extension, which will log all encountered problems, and if you could run it for me and send me the log, I should be able to fix it.

Thanks!

**Comment by hauberg** [comment] 2014-12-02 06:51
Hi,

Thanks for the reply! :-)

I'm using Gnome 3.14.2.

The extension reports no errors in LookingGlass.

I think I should be able to install from Github (I haven't tried that before, but I should be able to work it out).

Thanks again!

**Comment by N-Yuki** [comment] 2014-12-06 15:34
Hi hauberg,

I haven't been able to reproduce this problem.
Could you also give me a list of extensions you have installed? It might be having incompatibilities with another extension. If so, I will see what can be changed to make it compatible.

Also, if you want to try using the 3.14.2+ branch (https://github.com/N-Yuki/gnome-shell-extension-workspace-isolated-dash/tree/3.14.2%2B) of this extension, you can give that a go, but it looks like it's most likely a compatibility problem with another extension.

Thanks!

**Comment by hauberg** [comment] 2014-12-06 17:13
Hi,

I have the following extensions activated:

  "Dash to Dock": https://extensions.gnome.org/extension/307/dash-to-dock/
  "No topleft Hot Corner": https://extensions.gnome.org/extension/118/no-topleft-hot-corner/

and that's it.

Thanks again for looking at this problem!

**Comment by N-Yuki** [comment] 2014-12-07 17:54
Hi,

I had a look at "Dash to Dock", but it seems to be that this extension is the one causing incompatibilities. 
I've now found the conflicting code (https://github.com/micheleg/dash-to-dock/commit/8d2ccc73b79a483126bd1b23e6fe0de356dd7c73). Their workaround to accommodate 3.14.0 and 3.14.1 is what breaks compatibility with my extension. I think it can only be fixed on their end by adding an extra check in that function:

```
if (AppIcon.prototype._updateRunningStyle) {
  this.parent();
} else {
  ...their workaround code...
}
```

It seems to be a temporary workaround for them, so this bug will hopefully disappear in Shell 3.16, but if you want it to work with 3.14, I think they need to make the above change to make these extensions compatible.

**Comment by hauberg** [comment] 2014-12-08 08:35
Thanks for inspecting this.  I'll bring your findings to the developers of Dash to Dock.

Thanks!

**Comment by micheleg** [comment] 2014-12-11 00:59
@N-Yuki : would you mind briefly explaining your proposed workaround? I'm happy to apply  it if it helps to maintain the extensions compatibility.

**Comment by N-Yuki** [comment] 2014-12-11 22:38
@micheleg (https://github.com/micheleg/dash-to-dock/issues/126): Thank you for getting in touch.
The problem we have here is that your workaround to support 3.14.0 and 3.14.1 is to provide your own copy of the _updateRunningStyle() function, but my extension injects into the original version of that function. This causes my extension to not affect your Dash.

I haven't tried it out, so I may not have all the details, but I think a solution to fix this is to check if AppIcon.prototype._updateRunningStyle() is defined, and if so, you can assume that it is Shell >=3.14.2, so you can just call the original function.
If AppIcon.prototype._updateRunningStyle() is undefined, then you can call the old AppIcon.prototype._onStateChanged() function instead.

**Comment by micheleg** [comment] 2014-12-15 01:04
Please have a look at the workspace_separation_support branch, and test if it's working for you both on 3.14 and 3.14.1

**Closed as completed** 2015-02-18 00:05 UTC
