### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by CubeTheThird** [N-Yuki/gnome-shell-extension-workspace-isolated-dash#7] opened 2016-05-01 20:00 UTC
When I have this extension enabled, the memory usage of Gnome Shell increases from an normal ~250-300 MB to over 1 GB. I suspect it has to do with frequent closing and opening of windows/applications, but I haven't thoroughly tested it.

**Comment by franglais125** [comment] 2016-05-13 16:35
I encounter the same problem, on gnome-shell 3.14. After RAM usage gets too high, the shell becomes sluggish.

@CubeTheThird Do you happen to use dash-to-dock?

**Comment by CubeTheThird** [comment] 2016-05-14 04:21
I do not use dash-to-dock. Also, just to mention it, I'm using gnome-shell 3.20.2

**Comment by N-Yuki** [comment] 2016-08-06 10:34
Thanks for the report and sorry for the late response.
I don't see any memory issues directly in this extension, but it might also be caused by some internal changes in Gnome Shell. When I next push out an update, I'll see if I can make some changes to minimise the chances of a memory leak, and I might take a look to see if there's anything in Gnome Shell itself that may be responsible.

**Comment by CubeTheThird** [comment] 2016-08-21 00:18
Looks like the issue(s) may have been corrected. I've been running the extension after the last update for about 2 days, and the memory usage appears to be consistent every time I check it. I'll keep an eye out for the next little while to be certain.

**Comment by N-Yuki** [comment] 2016-08-21 09:46
Okay, thanks for the update! I'll close this bug now, but feel free to open it again if it's still an issue.

**Closed as completed by N-Yuki** 2016-08-21 09:46 UTC
